image: docker.io/qazando/appium-maven

stages:          # List of stages for jobs, and their order of execution
  - test

variables:
  BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}

test-job:       # This job runs in the build stage, which runs first.
  stage: test
  script:
    - export BROWSERSTACK_KEY=${BROWSERSTACK_KEY}
    - mvn test -Dexecucao=devicefarm -Ddispositivo=android