image: docker.io/qazando/appium-maven

stages:          # List of stages for jobs, and their order of execution
  - test
  - report
  - upload

variables:
  BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
  DEVICE: "android"  # Valor padrão, pode ser sobrescrito

test-job:       # This job runs in the build stage, which runs first.
  stage: test
  script:
    - export BROWSERSTACK_KEY=${BROWSERSTACK_KEY}
    - mvn test -Dexecucao=devicefarm -Ddispositivo=${DEVICE}
  artifacts:
    paths:
      - target/formated-report

report-job:       # This job runs in the build stage, which runs first.
  stage: generate
  dependencies:
    - test-job
  script:
    - echo "Uploading artifact..."
    -

upload-report-job:       # This job runs in the build stage, which runs first.
  stage: upload
  dependencies:
    - test-job
  script:
    - echo "Generating artifact..."
    - mvn cluecumber-report:reporting
  artifacts:
    paths:
      - target/formated-report
    only:
      - master