name: Run Appium Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      device:
        description: 'Device platform to run tests on'
        required: true
        default: 'android'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      appium:
        image: appium/appium
        options: --privileged
        ports:
          - 4723:4723

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        env:
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
        run: mvn test -Dexecucao=devicefarm -Ddispositivo=${{ github.event.inputs.device }}

      - name: Generate report
        run: mvn cluecumber-report:reporting

      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        with:
            name: test-report
            path: target/formated-report