name: Run Appium Tests on Android

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      appium:
        image: appium/appium
        options: --privileged
        ports:
          - 4723:4723

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        run: mvn test -Dexecucao=local -Ddispositivo=android
